add worktrunk installer and abort on empty version in github_install_logic

diff --git a/nq b/nq
--- a/nq
+++ b/nq
@@ -59,6 +59,7 @@ github_install_logic() {
     ver=`download ${url} |\
         grep 'tag_name' | grep -v "nightly" | grep -v -i alpha | grep -v "stable" |\
         head -n 1 | cut -d\" -f4`
+    [ -z "$ver" ] && log "[$1] failed to fetch version (API rate limited?), abort" && return 1
     [ "$curr" = "$ver" ] && log "[$1] $ver is the latest, return" && return
     log "[$1] will install $ver, current: $curr"
     $4 $ver $curr
@@ -397,6 +398,21 @@ install_cloudflared() {
             url=`download_url $repo $1 "cloudflared-linux-amd64"`
             download $url > "$tmp/$app" && chmod +x "$tmp/$app"
         fi
+        mv "$tmp/$app" "$bin_dir"
+    }
+    github_install_logic $app ${app}_version $repo ${app}_install
+}
+
+install_worktrunk() {
+    app=wt
+    repo="max-sixty/worktrunk"
+    wt_version() {
+        echo "`wt --version|cut -d' ' -f2`"
+    }
+    wt_install() {
+        ar=`[ $ARCH = "Darwin" ] && echo "aarch64-apple-darwin" || echo "x86_64-unknown-linux-musl"`
+        url=`download_url $repo $1 "worktrunk-$ar.tar.xz"`
+        download $url | tar -C $tmp --strip-components=1 -xJf -
         mv "$tmp/$app" "$bin_dir"
     }
     github_install_logic $app ${app}_version $repo ${app}_install
